metadata:
  name:  Anebix Main CSS
  output:  /css/anebix-main.css
  description: All of Anebix's CSS, all in one file
  author: Anebix
  authorId:  1249116126139519009
  source:  http://github.com/anebix-world/discord-css
  version: 0.0.2
  website:  https://anebix.neocities.org
  invite: vpQtzES4sn
  tags:
    - theme
    - custom
    - merged
  minify: true
  preserve_metadata: true

snippets:
  - repo: anebix-world/discord-css
    branch: main
    css_path: css/anebix-tweaks.css
    order: 1
  - repo: anebix-world/discord-css
    branch: main
    css_path: css/toggleable/add-servers-mentionedfirst.css
    order: 2
  - repo: anebix-world/discord-css
    branch: main
    css_path:  css/toggleable/change-channels-unreadpill.css
    order: 3
#  - repo: aushevahmad/awesome-css
#    branch: main
#    css_path:  modules/custom-emoji-bar.css
#    order: 4
  - repo: aushevahmad/awesome-css
    branch: main
    css_path: modules/vc-membercount.css
    order: 5
